# Generated by Django 3.1.7 on 2021-04-29 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0003_create_aduanas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.IntegerField()),
                ('tipo_documento', models.CharField(default='', max_length=10)),
                ('primer_nombre', models.CharField(default='', max_length=45)),
                ('segundo_nombre', models.CharField(default='', max_length=45)),
                ('tercer_nombre', models.CharField(default='', max_length=45)),
                ('primer_apellido', models.CharField(default='', max_length=35)),
                ('segundo_apellido', models.CharField(default='', max_length=35)),
                ('tercer_apellido', models.CharField(default='', max_length=35)),
                ('sexo', models.CharField(default='', max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nacionalidades', to='paises.pais', verbose_name='nacionalidad')),
                ('pais_residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residencias', to='paises.pais', verbose_name='residencia')),
            ],
        ),
    ]
