# Generated by Django 3.1.7 on 2021-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0001_creacion_viajeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajero',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
