# Generated by Django 3.1.7 on 2021-04-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0002_add_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajero',
            name='tercer_apellido',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='viajero',
            name='tercer_nombre',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
    ]
