# Generated by Django 3.1.7 on 2021-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pais',
            name='abreviatura',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre_nacionalidad',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(default='', max_length=30),
        ),
    ]
