# Generated by Django 3.1.7 on 2021-05-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0003_create_aduanas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduana',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aduanas', to='paises.pais', verbose_name='pais'),
        ),
    ]
