# Generated by Django 3.1.7 on 2021-04-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipajeExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(max_length=255)),
                ('valor_dolares', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrecioso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('clase', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleValoresMonetarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_dolares', models.DecimalField(decimal_places=2, max_digits=9)),
                ('origen_fondos', models.TextField(max_length=255)),
                ('destino_fondos', models.TextField(max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='monedas.materialprecioso', verbose_name='material')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monedas', to='monedas.moneda', verbose_name='moneda')),
            ],
        ),
    ]
