# Generated by Django 3.1.7 on 2021-04-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_add_bitacora'),
        ('monedas', '0001_create_monedas_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallevaloresmonetarios',
            name='bitacora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detallesValoresMonetarios', to='bitacora.bitacora', verbose_name='bitacora'),
        ),
        migrations.AddField(
            model_name='equipajeextra',
            name='bitacora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipajes_extra', to='bitacora.bitacora', verbose_name='bitacora'),
        ),
    ]
