# Generated by Django 3.1.7 on 2021-04-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_creacion_transporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporte',
            old_name='id_empresa',
            new_name='empresa',
        ),
    ]
