# Generated by Django 3.1.7 on 2021-04-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_auto_20210427_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='empresa',
        ),
        migrations.AddField(
            model_name='transporte',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='empresa_transporte',
        ),
    ]
