# Generated by Django 3.1.7 on 2021-04-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0002_creacion_paises'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='', max_length=8)),
                ('fecha', models.DateField()),
                ('motivo_viaje', models.CharField(default='', max_length=20)),
                ('numero_familiares', models.IntegerField()),
                ('cantidad_equipaje', models.IntegerField()),
                ('cantidad_no_acompanado', models.IntegerField()),
                ('dinero_mayor_diezmil', models.BooleanField()),
                ('animales_plantas_alimentos', models.BooleanField()),
                ('producto_quimico_sustancias', models.BooleanField()),
                ('mercancias_distintas', models.BooleanField()),
                ('exoneraciones_tributos', models.BooleanField()),
                ('pais_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paises', to='paises.pais', verbose_name='pais')),
            ],
        ),
    ]
