# Generated by Django 3.1.7 on 2021-04-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0003_create_aduanas'),
        ('bitacora', '0001_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='animales_plantas_alimentos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='dinero_mayor_diezmil',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='exoneraciones_tributos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='mercancias_distintas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='pais_procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paises_bitacora', to='paises.pais', verbose_name='pais'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='producto_quimico_sustancias',
            field=models.FloatField(),
        ),
    ]
