# Generated by Django 3.1.7 on 2021-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_fix_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.SmallIntegerField(choices=[(1, 'Creado'), (2, 'Validado'), (3, 'Terminado')], default=1),
        ),
    ]
